export const personalInfo = {
  name: 'Shreya Katiyar',
  role: 'Frontend Developer',
  tagline: 'Building beautiful, performant web experiences that users love.',
  bio: `I'm a Frontend Developer with 1+ years of experience crafting production-grade web applications.
  I specialize in React.js and Next.js, bringing a designer's eye and an engineer's precision to every project.
  I thrive at the intersection of great UX and clean code — building interfaces that feel fast, intuitive, and delightful.`,
  email: 'shreyakatiyar76@gmail.com',
  github: 'https://github.com/shreya-katiyar',
  linkedin: 'https://linkedin.com/in/shreya-katiyar',
  instagram: 'https://www.instagram.com/yrrrr_shreya/',
  location: 'India',
  available: true,
}

export const stats = [
  { value: 1, suffix: '+', label: 'Years of Experience' },
  { value: 5, suffix: '+', label: 'Projects Shipped' },
  { value: 10, suffix: '+', label: 'Technologies' },
  { value: 100, suffix: '%', label: 'Passion for UI' },
]

export const experiences = [
  {
    id: 1,
    role: 'Frontend Developer',
    company: 'Medicloud Global Private Limited',
    companyInitial: 'M',
    companyColor: '#3B82F6',
    companyUrl: 'https://www.linkedin.com/company/medicloudglobal/?originalSubdomain=in',
    duration: 'Mar 2025 – Present',
    type: 'Full-time',
    location: 'Remote',
    description:
      'Built and optimized production-ready healthcare e-commerce solutions featuring Cart, Checkout, Orders, Wishlist, and Authentication modules. Leveraged React.js, Docker, Postman, and REST APIs to deliver scalable, high-performance, and user-focused web applications.', 
    tech: ['React.js', 'JavaScript', 'CSS3', 'Docker', 'Postman', 'REST APIs', 'Microservices','Figma'],
    current: true,
  },
  {
    id: 2,
    role: 'Frontend Developer Intern',
    company: 'NTS Nihon Global',
    companyInitial: 'N',
    companyColor: '#8B5CF6',
    companyUrl: 'https://www.linkedin.com/company/nts-nihon-global/?originalSubdomain=in',
    duration: 'Jun 2025 – Aug 2025',
    type: 'Internship',
    location: 'Remote',
    description:
     ' Developed scalable React.js interfaces and reusable UI components with API integrations, improving application responsiveness, maintainability, and user experience.',
    tech: ['React.js', 'JavaScript', 'Bootstrap', 'Tailwind CSS', 'REST APIs', 'Debugging'],
    current: false,
  },
  {
    id: 3,
    role: 'Web Developer Intern',
    company: 'Rixi Labs',
    companyInitial: 'R',
    companyColor: '#10B981',
    companyUrl: 'https://rixilab.tech/',
    duration: 'Aug 2025 – Sep 2025',
    type: 'Internship',
    location: 'Remote',
    description:
      'Created modern, responsive web applications with a strong focus on performance optimization, clean architecture, and seamless cross-platform user experiences.',
    tech: ['React.js', 'Bootstrap', 'Tailwind CSS', 'Testing', 'Debugging'],
    current: false,
  },
]

export const projects = [
  {
    id: 1,
    title: 'GymTech',
    subtitle: 'Fitness Tracking App',
    description: 'Modern fitness tracking and workout planning app with progress visualization and personalized training recommendations.',
    tech: ['React.js', 'JavaScript', 'Tailwind CSS', 'Bootstrap', 'REST APIs'],
    github: 'https://github.com/shreyakatiyar/Gym_tech',
    live: 'https://gym-tech-ten.vercel.app',
    featured: true,
    accentColor: '#3B82F6',
    icon: '💪',
    category: 'Frontend',
    status: 'Live',
  },
  {
    id: 2,
    title: 'Imaginary AI',
    subtitle: 'AI-Powered Tool',
    description: 'An intelligent AI-driven application leveraging modern machine learning capabilities for enhanced, creative user experiences.',
    tech: ['React.js', 'JavaScript', 'AI APIs', 'REST APIs'],
    github: 'https://github.com/shreyakatiyar/Imaginary-AI',
    live: 'https://imaginary-ai-sandy.vercel.app',
    featured: true,
    accentColor: '#818CF8',
    icon: '🤖',
    category: 'AI',
    status: 'Live',
  },
  {
    id: 3,
    title: 'Interactive Learning',
    subtitle: 'EdTech Platform',
    description: 'An interactive e-learning platform for engaging educational experiences with modern UI/UX design and smooth interactions.',
    tech: ['React.js', 'JavaScript', 'CSS3', 'Bootstrap'],
    github: 'https://github.com/shreyakatiyar/Interactive-Learning',
    live: 'https://interactive-learning-sand-six.vercel.app',
    featured: false,
    accentColor: '#38BDF8',
    icon: '📚',
    category: 'Frontend',
    status: 'Live',
  },
  {
    id: 4,
    title: 'RecipeFinder',
    subtitle: 'Food Discovery App',
    description: 'Discover and explore recipes with smart filtering, ingredient-based search, and a beautiful, responsive recipe card UI.',
    tech: ['React.js', 'JavaScript', 'REST APIs', 'CSS3'],
    github: 'https://github.com/shreyakatiyar/RecipeFinderApp',
    live: 'https://recipe-finder-app-silk.vercel.app',
    featured: false,
    accentColor: '#60A5FA',
    icon: '🍳',
    category: 'Frontend',
    status: 'Live',
  },
  {
    id: 5,
    title: 'Stellar Precision',
    subtitle:'Scientific Instruments Showcase',
    description: 'A modern product showcase platform for scientific instruments featuring elegant UI, interactive visual elements, and a high-end user experience built with React and TypeScript.',
   tech: ['React.js', 'TypeScript', 'JavaScript', 'CSS3', 'REST APIs'],
    github: 'https://github.com/shreyakatiyar/Stellar-Precision',
    live: 'https://stellar-precision-rho.vercel.app',
    featured: true,
    accentColor: '#A5B4FC',
    icon: '✨',
    category: 'Frontend',
    status: 'Live',
  },
  {
    id: 6,
    title: 'After You',
    subtitle:'Women Wellness & Support Platform',
   description: 'A comprehensive wellness platform designed to empower women through self-care services, community storytelling, mental well-being resources, and interactive digital experiences.',
    tech: ['HTML5', 'CSS3', 'JavaScript', 'Animations'],
    github: 'https://github.com/shreyakatiyar/After-you',
    live: 'https://after-you-wheat.vercel.app',
    featured: false,
    accentColor: '#94A3B8',
    icon: '🎨',
    category: 'Design',
    status: 'Live',
  },
]

export const skillCategories = [
  {
    title: 'Frontend',
    icon: '⚡',
    color: 'terra',
    skills: [
      { name: 'React.js', level: 92 },
      { name: 'Next.js', level: 88 },
      { name: 'JavaScript', level: 90 },
      { name: 'HTML5', level: 95 },
      { name: 'CSS3', level: 92 },
       { name: 'Redux', level: 72 },
    ],
  },
  {
    title: 'Styling & Design',
    icon: '🎨',
    color: 'olive',
    skills: [
      { name: 'Tailwind CSS', level: 90 },
      { name: 'Bootstrap', level: 85 },
      { name: 'Responsive Design', level: 92 },
      { name: 'UI/UX Design', level: 85 },
      { name: 'Figma', level: 80 },
      { name: 'Framer Motion', level: 70 },
    ],
  },
  {
    title: 'Backend & Tools',
    icon: '🛠️',
    color: 'lav',
    skills: [
      { name: 'REST APIs', level: 88 },
      { name: 'Git & GitHub', level: 88 },
      { name: 'Docker', level: 72 },
      { name: 'Postman', level: 85 },
      { name: 'Microservices', level: 75 },
      { name: 'Performance Opt.', level: 82 },
    ],
  },
]

export const achievements = [
  {
    id: 1,
    icon: '🏥',
    title: 'Production Platform',
    description: 'Shipped a healthcare e-commerce platform serving thousands of users in production',
    metric: '800+ users',
    color: 'lav',
  },
  {
    id: 2,
    icon: '⚡',
    title: 'Performance Champion',
    description: 'Reduced page load times by 40% through code splitting, lazy loading, and optimization',
    metric: '40% faster',
    color: 'terra',
  },
  {
    id: 3,
    icon: '🎯',
    title: 'API Integration',
    description: 'Integrated 80+ complex REST APIs across multiple microservices in a healthcare domain',
    metric: '10+ APIs',
    color: 'olive',
  },
  {
    id: 4,
    icon: '📦',
    title: 'Docker Mastery',
    description: 'Containerized development environments reducing team onboarding time significantly',
    metric: '60% faster onboarding',
    color: 'lav',
  },
  {
    id: 5,
    icon: '🎨',
    title: 'UI/UX Excellence',
    description: 'Delivered pixel-perfect, responsive UIs across all device sizes with 100% fidelity to designs',
    metric: 'All devices',
    color: 'terra',
  },
  {
    id: 6,
    icon: '🚀',
    title: 'Fast Learner',
    description: 'Expanded skill set from HTML/CSS to full React/Next.js production engineer in under 1 year',
    metric: '1 year journey',
    color: 'olive',
  },
]

export const navLinks = [
  { href: '#about', label: 'About' },
  { href: '#experience', label: 'Experience' },
  { href: '#projects', label: 'Projects' },
  { href: '#skills', label: 'Skills' },
  { href: '#contact', label: 'Contact' },
]
